[package]
name = "best-crate"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cwd-voting = { version = "0.2.0", git = "https://github.com/DA0-DA0/dao-contracts" }